version: "~> 1.0"
language: node_js
os: linux
dist: focal
if: branch = "stable" OR tag IS present
jobs:
  include:
  - stage: Build project
    name: Build the project on Linux with NodeJS 14
    os: linux
    dist: focal
    node_js: '14'
    script: npx tsc
  - stage: Release to NPM
    name: Publish the package to the npmjs repository
    os: linux
    dist: focal
    node_js: '14'
    script: npx tsc
    deploy:
      edge: true
      provider: npm
      email: npmjs@eraud.dev
      api_key:
        secure: psejUO/u17HN7q1elx1v9pNyKxVnlaNIlO7ClKRGCqjllYCckQECz8B8Y3SVGBpe1HT4AhreSTtW39WfwxA4DqsFkbf3NEmrI2s9cOivq6SwywgRSntzfHwsUo76pIVR8lP1d4UHmWVSA4OGq4WW6R5TtbaW3/1XMz9Q/wbp+ERrwnJR2u/wgLCpJe7g47T3c/NiqZ9wweBm8onhx91E1p1mY3jN+zrBJ3CH3C04I5BkAKFKar9RXqulR0QjKfjE5Yd0XHiu9g6yt3mp+SBos0vNAUtcCVuqLjTTaLWqlQrGfVccshEmxYfV1iNKeP9eIUk5q8Zxs+7nje7/hCNaq0dmJcc2UEC0y1axEeUIzvBrR4KpPy46BpHlrKzkDlYtoEF7SangE8A1ugZ5eNnEPqi662sBk0l9lYsCRf5FEHS+EYQEH8lGXg742V/4R/8GVHtoVKVkw5ZVpEi/6j4fojf7tz1GT2NW+ufhBK4JRF6OHzBbZ9frZLB+cNhto/ia6ZQrgTzgi7DQJSqsIZrqoTOwlUzFPNXKAhMhnb1U+wMuOFwT+O+lO0iX5LZqAbg7y1s4MhTHaQSh+07mxpwOHza3HN82myEOBmzbzqGiAc5Qc6hPLWG9+rfwFnvl8iIp3mi1QqMN1GmnDa8ZQO1kOPzk3TUT44spjbBN4s81uKo=
      on:
        tags: true
        repo: lesjoursfr/media-converter
        branch: stable
      cleanup: false
notifications:
  slack:
    secure: bHZg4yvYvYaYHsh/bE9YfnX5nd83Dh4+obucoE0RSczwXL0FohwE01o3IQ5z8J/B+5ggrVPwWYFxPEH+dcpVSin2+UJgxlDn4CbQBlFBg1WOnJavRze2I3nH+x6jk10p0ndYe4EJ4b4+F4hew8YoU9FhjO48R+FbbcoMzqQ5Md2VVzf8Y2qP4k4Bs1z6xzoyl+12vbbkE1zHf7gYLiRVZhPwjx7T0lgjklI9kdZWboGnEs9CC+ZeHeoIhIcaJ+fUJV7rqCS/iXCSzrRX5T7TOmzKlxfVz9oXNaecDQF0iTk5JkmyJP45WMHGq0P0sJ0M/xtRVhiAxkm9Eydz2sSE9qzs9KygmdLELm0QixFLFLg7wq/RLUW2PstDdk7WQ0fOCm/v67HzJoplJNdEmrd9saXRoBmkWI8Y5k1jgN3NWnCXhXmWfUKLTOwt2wHbUiqdOsFdL0NicHVvgmTBO/ozoEI3/W48Z0nOWcV6L6u2/Kbei1GavbE7RNfuEhZwHF7SG69Eu6aU4Cv//lSkTavhndnW57Jka6IzybXXSRbgR8lOXBB3yvwDyxk6Dbzkmfhj63dLBkordR/wGQ5PJCrtzcQhwTcRSz4KPuJEk8zcIj2KH6JyIZP/sFAsTOB9t1KG2+suG5ESRDCKCmrVPKyZfT2eB/jBrRjiw8Ntj6vvxMg=
